export const PUBLIC_ROUTE = ["/login", "/verify-otp", "/register"];

export const genreTVOption = [
  { name: "Romance", value: "ROMANCE" },
  { name: "Crime", value: "CRIME" },
  { name: "Horror", value: "HORROR" },
  { name: "Action", value: "ACTION" },
  { name: "Comedy", value: "COMEDY" },
  { name: "Drama", value: "DRAMA" },
  { name: "Sci-Fi", value: "SCI-FI" },
  { name: "Fantasy", value: "FANTASY" },
  { name: "Historical", value: "HISTORICAL" },
  { name: "Documentary", value: "DOCUMENTARY" },
  { name: "Others", value: "OTHERS" },
];

export const genreShortsOption = [
  { name: "Comedy & Humor", value: "COMEDY_AND_HUMOR" },
  { name: "People", value: "PEOPLE" },
  { name: "Beauty", value: "BEAUTY" },
  { name: "Sports", value: "SPORTS" },
  { name: "Fashion & Lifestyle", value: "FASHION_AND_LIFESTYLE" },
  { name: "Gaming", value: "GAMING" },
  { name: "Food & Drink", value: "FOOD_AND_DRINK" },
  { name: "Travel & Holidays", value: "TRAVEL_AND_HOLIDAYS" },
  { name: "Automobile", value: "AUTOMOBILE" },
  { name: "Science & Technology", value: "SCIENCE_AND_TECHNOLOGY" },
  { name: "Health & Fitness", value: "HEALTH_AND_FITNESS" },
  { name: "Animals & Pets", value: "ANIMALS_AND_PETS" },
  { name: "Family & Parenting", value: "FAMILY_AND_PARENTING" },
  { name: "Home & DIY", value: "HOME_AND_DIY" },
  {
    name: "Self Help & Motivational",
    value: "SELF_HELP_AND_MOTIVATIONAL",
  },
  { name: "Business & Finance", value: "BUSINESS_AND_FINANCE" },
  { name: "Movies & Entertainment", value: "MOVIES_AND_ENTERTAINMENT" },
  { name: "Others", value: "OTHERS" },
];

export const industryOptions = [
  { name: "Grocery", value: "GROCERY" },
  { name: "CPG", value: "CPG" },
  { name: "Ecommerce", value: "ECOMMERCE" },
  { name: "Beauty & Personal Care", value: "BEAUTY & PERSONAL CARE" },
  { name: "Health & Wellness", value: "HEALTH & WELLNESS" },
  { name: "Fintech", value: "FINTECH" },
  { name: "Telecom", value: "TELECOM" },
  { name: "Auto", value: "AUTO" },
  { name: "Travel & Hospitality", value: "TRAVEL & HOSPITALITY" },
  { name: "F&B", value: "FB" },
  { name: "Consumer Electronics", value: "CONSUMER ELECTRONICS" },
  { name: "BFSI", value: "BFSI" },
  { name: "Apparel", value: "APPAREL" },
  { name: "Technology", value: "TECHNOLOGY" },
  { name: "Real Estate", value: "REAL ESTATE" },
  { name: "Utilities", value: "UTILITIES" },
  { name: "Jewellery", value: "JEWELLERY" },
  { name: "Media & Entertainment", value: "MEDIA & ENTERTAINMENT" },
  { name: "Others", value: "OTHERS" },
];
