import type { Metadata } from "next";
import "@repo/ui/globals.css";
import {Roboto} from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'], 
  weight: ['400','500','700'], 
  style: ['normal', 'italic'],
});
export const metadata: Metadata = {
  title: "Concept Map",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        {children}
      </body>
    </html>
  );
}
