import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@repo/ui/globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Include the font weights you need
  style: ["normal", "italic"], // Optional: include styles
});

export const metadata: Metadata = {
  title: "Concept Map",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>{children}</body>
    </html>
  );
}
